#tag::graphiql[]
graphql:
  graphiql.enabled: true
#end::graphiql[]
---
#tag::datasource[]
datasources:
  default:
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE
    initialization-fail-timeout: 10000

#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true
#end::flyway[]

logger:
  levels:
    example.micronaut: DEBUG
    wqp: DEBUG
