
micronaut:
  executors:
    io:
      # The number of threads available for IO tasks, which will tie to the number
      # of concurrent requests that can be handled.
      # See https://docs.micronaut.io/2.0.0.M2/guide/index.html#reactiveServer
      type: fixed
      nThreads: 75

graphql:
  graphiql.enabled: true


datasources:
  default:
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE
    initialization-fail-timeout: 10000


---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true
#end::flyway[]

logger:
  levels:
    example.micronaut: DEBUG
    wqp: DEBUG
